### ISSUE TITLE
Too long inserts attempted (maximum number of expressions in a list exceeded, expected at most 16,384, got 98,508)

### ISSUE THREAD

**Issue by ztane** [snowflakedb/snowflake-sqlalchemy#92]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Python 3.6.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic

3. What are the component versions in the environment (`pip list`)? 

```
asn1crypto (0.24.0)
azure-common (1.1.18)
azure-storage-blob (1.5.0)
azure-storage-common (1.4.0)
boto3 (1.9.130)
botocore (1.12.130)
certifi (2019.3.9)
cffi (1.12.2)
chardet (3.0.4)
cryptography (2.6.1)
docutils (0.14)
future (0.17.1)
idna (2.8)
ijson (2.3)
inflect (2.1.0)
jmespath (0.9.4)
pip (9.0.1)
pkg-resources (0.0.0)
psycopg2 (2.8.1)
pycparser (2.19)
pycryptodomex (3.8.1)
PyJWT (1.7.1)
pyOpenSSL (19.0.0)
python-dateutil (2.8.0)
pytz (2018.9)
requests (2.21.0)
s3transfer (0.2.0)
setuptools (39.0.1)
six (1.12.0)
snowflake-connector-python (1.7.10)
snowflake-sqlalchemy (1.1.11)
sqlacodegen (2.0.1)
SQLAlchemy (1.3.2)
urllib3 (1.24.1)
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Add a sizable number of ORM objects (in the ten-thousand range with 12 columns each) into Session, then flush-commit in one go

5. What did you expect to see?

Things working

6. What did you see instead?

sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001795 (42601): 018b6efe-0063-7ca9-0000-00001d29a0a9: SQL compilation error: error line 1 at position 344
maximum number of expressions in a list exceeded, expected at most 16,384, got 98,508

7. Can you set logging to DEBUG and collect the logs?

Too much data

--- 

The error has been detailed in the Connector issue https://github.com/snowflakedb/snowflake-connector-python/issues/37 - the "solution" is setting `snowflake.connector.paramstyle = 'qmark'`. This should be the setting that SQLAlchemy connections *should* use to avoid the spurious errors. 

OTOH it can be seen as an error in the Connector, as https://github.com/snowflakedb/snowflake-connector-python/blob/5be6b8c6531aac7c2ca3858be784c5f5f714a0e4/cursor.py#L688  should be aware of the limitation and do only maximum of 16384 per one `conn.execute` invocation!

**Comment by ztane** [comment]
Switching to `qmark` is currently not a solution either, as a bug in the connector (https://github.com/snowflakedb/snowflake-connector-python/issues/168) causes the `None`s not be mapped to NULLs.

**Comment by keller00** [comment]
Sorry @ztane for not answering you earlier, it appeared as you answered your own question.
We can pretty quickly fix whatever issue you encounter with `qmark` in the connector, but right now we won't have time to make `snowflake-sqlalchemy`'s engine switch on it's own.
However; for the future let's leave this issue open as a reminder.
Let us know if you run into any other issues with `qmark` and thank you for your patience!

**Comment by smtakeda** [comment]
This was fixed in v1.7.11. Try and let me know.

**Comment by chetansurwade** [comment]
Issue still exists in release 1.2.3 release. Kindly merge and make a release if possible.

**Comment by steve-dyno** [comment]
Hey @smtakeda, I am confused by your comment. The latest version is v1.2.4, and I don't see v1.7.11?  I still see this issue in v1.2.4.  Setting to qmark does not really work as a workaround as mentioned above.

**Comment by smtakeda** [comment]
@steve-dyno , sorry, I meant Python connector v1.7.11. https://pypi.org/project/snowflake-connector-python/. That version includes the fix for `None` binding in the `qmark` mode.
